language: python
sudo: required
dist: xenial
env:
  global:
  - secure: v6DgmeN21a+K7QU7/DXjowEkDB/F536MwPzPLy2Cip7ajMSehSNU2tR0WmOt4EDpr0NtwMgjiGPwtv0Nn0wjM298PTJcVT7DlvbkuALl34NkdOqoBHuh35M50WtIyWYy2nbvnix5x76eViQ0TKnE2UuAsbsB8Du5tigTN8lxtzY6g9HZEmnd5FImUfW+EaGBmoyE1C2YCNKfYljo0AuviIXbFhMI0h52asrsD7jGl7mbTYdXhu4n1xMYLNWy9n2oqniBYtXlFLaiNP8m4zjBkqHLSE79xT+ETKyLUCfHgMvkBqna2qGIADWXgHl1y6+mkxBLBB2jkptt+YNlLPC5Xp/VMH4TeiRhEOhad1VgyZOSaaVp/FEZOMDLGDOjp3tgt/P0SBLnvQeaxwelWCpebCFLatXo+tDySOiXgjJQaGjovR4de3/Ljupnh98as0SxxgywB0QIGYYHRvdQXDVirtjAHuGmdMDiKciwfvYw1/R0GS/qdqjTlhsde20uffT6VMyZgtNTnoR3JssT9P5j+3DKKJYF0YP9lSCQB/cLkQ7UgXjBOX3wCRKQJou8JJCefXaLdInyWNCQ6i/CBNwCLxYATJLtDEh7Qojlk10U2j4+lXeEoyvNi+kBM+W6Vpy0F0/4rVrvEqMSovedS5WMSF6js5T9uyKN9TUHzL/0dmM=
  - secure: NDP+TthsjCXHgQ7SORqStsgDcJij1pYFZuwT/mh8GltxNHQtsAA0p8gc+eZbjk89Vu+nvFpE9a0MAthJJQ2nBFZ4/18Es7Lggqq95vHBqUbNdrEc2u8ruvX7ad+lWS8QPr2EA0HyxK4EFgaNT30Hk6Vi6kugC6dBeSrPuk4D52Nf1yZC9HHxP54taB9Q3w9c97dpdXPWvaYAABzYJarm75t29IKJCxkPT5+b665NAxwBGQVB1o0xbdu67Fdq7R1Un8GPigTuZP8dfcaPdJ/rbM+NOKDza+OWJztSM8TQFk1ASzjS6AzofGKMB8BexJHrCQL2PSsPDxZ4FTEwheNJQ5D3DW6ia2C0RmA2UAysR1BzV+Ld0Mw48Dw7YQPjH6gnwYAYU0VH3J25p3F9nRE1ZoZZrweVhAsgoJy/QP/zph3kijsuRzn0+fj4U9+hJsDisVHHyDAi+Wm6rAJ1Mkl3CgvCSj6GJNSJDhd7JYpG5uRmvbC1Mw5sECj75ZlFlqWdKM08sD/RpdD2A6r0auCB415qz1kbUES/03sQSmd3PBKUgKyXacyEfpM4QBo+YlX8hwAoGk/q6DOjV43BUdfZcQvKMMwSRXzY0V8V5jlmPvsQrRijdaHUc6KWedz0xj/eWMLCGGSzQy3832lmVrMKM2WDAcfpczCSNUi6TaVFp74=
python:
- '3.6'
- '3.7'
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run flake8 --ignore=E501 rs3clans/
- poetry run pytest
before_deploy:
- poetry build
deploy:
  provider: script
  script: poetry publish -u $PYPI_USER -p $PYPI_PASS
  skip_cleanup: true
  on:
    repo: johnvictorfs/rs3clans.py
    branch: master
    tags: true
