language: python
sudo: required
dist: xenial
env:
  global:
  - secure: pgE+OgKEcB/fBEoAtxskRoHxtPhHXHFL3d1clfcCk0isJDLUYwRAmgQ4RRXukNHCPhVNyWDaFzhJUxQwGRKqFgrtY3NcNTP7+ggorf12A3DxzmfQZhT2cfik85MEaW3dRlcgpqFXIHkUkpe0qtInyI+zjs9MjGOwGS5FZfPAYfrEiLlQNT/SY20WJ63MrIEhnedqqha1ZMhxFGwNID24XN+DHPKxEVMSzc2wBwr2IZSI2d49B+5O5UropsS9v4Ll+ZHlCUkhg/cB+1OtFrZHCw2ezu8V42fa697jacp9TVqtxBPetvW4qFa1j+nD4cGFkyswf2799fuOsNwX7lJdKNWOZx+dc8VIu5ZQfwN9YK+/xODYhPkZ+zplLa1EtBsZYlQ94xp5JkDLF8/tW5CvAQ5gr2QexnxpvEHgcu0ntjooBq5FqO/vkBSDnyBfG1Zw2mPZ9oMBxQ7Hwm0DPjBIbkZTAZmCaiWEcyjfCDl0PqXF3WO8CdhiG8aoYebYEi+mwgbEGBdT2aF38HqDj+LMOhNAjgVt+qx5ZadJoD/+RCop+BZMlzesdx5WCjF2CpAcDAW+NneISW8NN+skGa21hQThGVW6F6enf3Duw8lXaDUtHx6t3iA8UF7LcEjxws4tG8xnMm3EanhAxQ2KZ3UogR+nkflfpL73R/zkXAijH2s=
  - secure: N64jkOJJY+USO4EdVE+GDw+WozqbLzf0mnDlzGQEnmqc5ipkDZUBJ9MiheSO1QXaNoFunbz1IZDJgyPKahpbOaYha8GY7j6DBsjd/nl+Pm3UQrgfpA4WHqliPFK0H6g36vSMc85Q4oc5W52lvHuNiZhDjBBOnNO908j8w+h4Ktq4l+CdwPAZrbc6WLcdp1bFxoqgZ860RZvWKv5Z564tF48LxfhQe5TVtOatXimyiWdwLuFJp3ryRsUUJI4REsp2cKr4xSm96NSbbc0hDXCMsMeYeUj3npCRM/2MN9bsysTnEH2CdJiFA/iZWAEXjU2rd5ONQhJr4aFGy+KlpUYatxOUiSMECEtk69RKVngXldUIzsD9lrYdA8t8HQ4epVerPcmk68NouKx95rHq1oh5HqojwaAbdTkU8TghUykTDimWE1mV8mbZRplQi0PIuEa15GyIdE8aHWHXaDfvTY8g3DBdO38oGlQmaSXo0NVlfDa0C0jSAGGL4l2gLxsQYM1Hff5q13bLZeCslXsVDvHpIOlQPk7Yjw0Z+tF410ZmvqhqCfVXr9LIBRaxHMavQ2f4dRCmnwaRDtK2rMO2Pcma7XYbVGu/59XJHZSP5d9GZypT/LiauoriHtj8CXbm1T24DPZZpL6sIG6Pso8NqLydoW2SAQs2QEOy9jD9zQBXAMo=
python:
- '3.6'
- '3.7'
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run flake8 --ignore=E501 rs3clans/
- poetry run pytest
before_deploy:
- poetry build
deploy:
  provider: script
  script: poetry publish -u $PYPI_USER -p $PYPI_PASS
  skip_cleanup: true
  on:
    repo: johnvictorfs/rs3clans.py
    branch: master
    tags: true
